import {
    decompress_t,
    full_ui_t,
    onInput,
    registerCompression,
    ui_t,
    updateMap,
    uploadInput,
} from "./api.js";
import { from_cart } from "../src/complex.js";
import {
    _Curve,
    CurveH,
    CurveSnake,
    CurveSpiral,
    CurveV,
} from "../src/curve.js";

onInput((val, up) => {
    // console.log(up, val);

    if (up === "*" || up === "map" || up === "input" || up === "downsample") {
        _updateMap(val);
    }

    if (up === "artifact" && val.dft && val.dft_cutoff && val.artifact) {
        // Check diffs
        const original = val.dft;
        const artifact = val.artifact.decompressed.dft;

        for (const component of ["r", "g", "b"] as const) {
            if (val.dft_cutoff[component] > artifact[component].length) {
                console.warn(
                    `Failed to compare ${component}-component; ${val.dft_cutoff[component]} > ${artifact[component].length}`,
                );
                continue;
            }

            // Compute sum of x/y component differencse
            let acc: number = 0;
            let ct: number = 0;
            for (let i = 0; i < val.dft_cutoff[component] && i < 2; i++) {
                const oX = original[component][i].re();
                const oY = original[component][i].im();
                const aX = artifact[component][i].re();
                const aY = artifact[component][i].im();

                acc += Math.pow(oX - aX, 2) + Math.pow(oY - aY, 2);
                ct += 2;
            }
        }
    }
});

function _updateMap(val: full_ui_t) {
    if (val.input === null) {
        updateMap("uninitialized");
        return;
    }

    const curves: _Curve[] = [];

    switch (val.map) {
        case "vertical":
            for (let x = 0; x < val.width; x++) {
                curves.push(new CurveV(x, 0, val.height - 1));
            }
            break;
        case "horizontal":
            for (let y = 0; y < val.height; y++) {
                curves.push(new CurveH(0, val.width - 1, y));
            }
            break;
        case "snake":
            curves.push(new CurveSnake(0, 0, val.width - 1, val.height - 1));
            break;
        case "spiral":
            curves.push(new CurveSpiral(0, 0, val.width - 1, val.height - 1));
            break;
    }

    updateMap({
        width: val.width,
        height: val.height,
        curves,
    });
}

/**
 * Compute size of file generated by the input state
 * @param state
 */
function compress(state: full_ui_t): ArrayBuffer {
    // Format: [Width][Height][Header<R>][Body<R>][Header<G>][Body<G>][Header<B>][Body<B>]  ; Overall file format
    // Width: 2 B                   ; Height of image
    // Height: 2 B                  ; Width of image
    // Header: [Length][Min][Max]   ; Header describing some color component
    // Length: 2 B                  ; Number of bytes in body
    // Min: 2 B                     ; This component's minimum value (excluding 0)
    // Max: 2 B                     ; This component's maximum value
    // Body: [X-Val][Y-Val]         ; Body containing color component data
    //                              ; Must LERP from [0, 255] to [min, max]

    if (!state.dft || !state.dft_cutoff) return new ArrayBuffer(); // Invalid

    const size =
        4 +
        3 * (2 + 4) +
        2 * (state.dft_cutoff.r + state.dft_cutoff.g + state.dft_cutoff.b);
    const buffer = new Uint8Array(size); // Underlying data

    // Count the current offset for allocation within buffer
    let bufferIndex = 0;

    // Set image dimensions
    buffer[bufferIndex++] = (state.width & 0x00ff) >> 0;
    buffer[bufferIndex++] = (state.width & 0xff00) >> 8;
    buffer[bufferIndex++] = (state.height & 0x00ff) >> 0;
    buffer[bufferIndex++] = (state.height & 0xff00) >> 8;

    // Fill out rest of buffer
    for (const component of ["r", "g", "b"] as const) {
        // ======== Header ========

        let min: number = 2 ** 16 - 1;
        let max: number = 0;

        // Get per-component min/max
        for (const v of state.dft[component]) {
            const x = v.re();
            const y = v.im();

            min = Math.min(min, x, y);
            max = Math.max(max, x, y);
        }

        const length = state.dft_cutoff[component];

        // Perform manual 2's complement
        // Avoids overflow condition

        const c_min = min < 0 ? 0x010000 + min : min;
        const c_max = min < 0 ? 0x010000 + max : max;

        buffer[bufferIndex++] = (length & 0x00ff) >> 0;
        buffer[bufferIndex++] = (length & 0xff00) >> 8;
        buffer[bufferIndex++] = (c_min & 0x00ff) >> 0;
        buffer[bufferIndex++] = (c_min & 0xff00) >> 8;
        buffer[bufferIndex++] = (c_max & 0x00ff) >> 0;
        buffer[bufferIndex++] = (c_max & 0xff00) >> 8;

        // Body

        // Push all elements into body in x/y order
        for (let i = 0; i < state.dft_cutoff[component]; i++) {
            const v = state.dft[component][i];

            const x = v.re();
            const y = v.im();

            // Determine magnitude of value
            const xb = Math.round(
                Math.min(Math.max((x - min) * (255 / (max - min)), 0), 255),
            );
            const yb = Math.round(
                Math.min(Math.max((y - min) * (255 / (max - min)), 0), 255),
            );

            buffer[bufferIndex++] = xb;
            buffer[bufferIndex++] = yb;
        }
    }

    return buffer.buffer;
}

function decompress(buf: ArrayBuffer): decompress_t {
    const buffer = new Uint8Array(buf);

    // Count the current offset for reading within buffer
    let bufferIndex = 0;

    // Read out dimensions
    const width = (buffer[bufferIndex++] << 0) | (buffer[bufferIndex++] << 8);
    const height = (buffer[bufferIndex++] << 0) | (buffer[bufferIndex++] << 8);

    // Extract DFT values
    const dft: decompress_t["dft"] = {
        r: [],
        g: [],
        b: [],
    };

    const full_length = Math.ceil((width * height) / 2);

    // Fill out rest of buffer
    for (const component of ["r", "g", "b"] as const) {
        const length =
            (buffer[bufferIndex++] << 0) | (buffer[bufferIndex++] << 8);
        let min = (buffer[bufferIndex++] << 0) | (buffer[bufferIndex++] << 8);
        let max = (buffer[bufferIndex++] << 0) | (buffer[bufferIndex++] << 8);

        // Perform manual 2's complement
        // Avoids overflow condition
        if (min & 0x8000) min = min - 0x010000;
        if (max & 0x8000) max = max - 0x010000;

        // Extract all elements into body from x/y order
        for (let i = 0; i < length; i++) {
            const xb = buffer[bufferIndex++];
            const yb = buffer[bufferIndex++];

            // Extract values
            const x = min + xb * ((max - min) / 255);
            const y = min + yb * ((max - min) / 255);

            // Combinate into a single complex number
            dft[component].push(from_cart(x, y));
        }

        // Pad missing DFT frequencies with (0, 0)
        for (let i = length; i <= full_length; i++) {
            dft[component].push(from_cart(0, 0));
        }
    }

    return {
        width,
        height,
        dft,
    };
}

registerCompression(compress, decompress);

// Mime image being uploaded
uploadInput(new URL("../test_imgs/16x16_target.png", import.meta.url));
