import {
    full_ui_t,
    onInput,
    registerCompressor,
    ui_t,
    updateMap,
    uploadInput,
} from "../src/api.js";
import {
    _Curve,
    CurveH,
    CurveSnake,
    CurveSpiral,
    CurveV,
} from "../src/curve.js";

onInput((val, up) => {
    // console.log(up, val);

    if (up === "*" || up === "map" || up === "input" || up === "downsample") {
        _updateMap(val);
    }
});

function _updateMap(val: full_ui_t) {
    if (val.input === null) {
        updateMap("uninitialized");
        return;
    }

    const curves: _Curve[] = [];

    switch (val.map) {
        case "vertical":
            for (let x = 0; x < val.width; x++) {
                curves.push(new CurveV(x, 0, val.height - 1));
            }
            break;
        case "horizontal":
            for (let y = 0; y < val.height; y++) {
                curves.push(new CurveH(0, val.width - 1, y));
            }
            break;
        case "snake":
            curves.push(new CurveSnake(0, 0, val.width - 1, val.height - 1));
            break;
        case "spiral":
            curves.push(new CurveSpiral(0, 0, val.width - 1, val.height - 1));
            break;
    }

    updateMap({
        width: val.width,
        height: val.height,
        curves,
    });
}

/**
 * Compute size of file generated by the input state
 * @param state
 */
function computeCompressionSize(state: ui_t): ArrayBuffer {
    // Format: [Header<R>][Body<R>][Header<G>][Body<G>][Header<B>][Body<B>] ; Overall file format
    // Header: [Length][Min][Max]   ; Header describing some color component
    // Length: 2 B                  ; Number of bytes in body
    // Min: 2 B                     ; This component's minimum value (excluding 0)
    // Max: 2 B                     ; This component's maximum value
    // Body: [X-Val][Y-Val]         ; Body containing color component data
    //                              ; Must LERP from [1, 255] to [min, max] to obtain the actual value,
    //                              ; With an input of `0` yielding a `0` output

    if (!state.dft || !state.dft_cutoff) return new ArrayBuffer(); // Invalid

    const size =
        3 * (2 + 4) +
        2 * (state.dft_cutoff.r + state.dft_cutoff.g + state.dft_cutoff.b);
    const buffer = new ArrayBuffer(size); // Underlying data

    // Count the current offset for allocation within buffer
    let bufferIndex = 0;

    // Fill out buffer
    for (const component of ["r", "g", "b"] as const) {
        // ======== Header ========

        let pre_min: number = 2 ** 16 - 1;
        let max: number = 0;

        // Get per-component min/max
        for (const v of state.dft[component]) {
            const x = v.re();
            const y = v.im();

            pre_min = Math.min(pre_min, x, y);
            max = Math.max(pre_min, x, y);
        }

        // Chop out all values that would evaluate to `0` in unsigned 8-bit LERP, as per spec
        // Then recompute `min`
        let min_thresh = pre_min + (max - pre_min) / 255;
        let min: number = 2 ** 16 - 1;
        for (const v of state.dft[component]) {
            const x = v.re();
            const y = v.im();

            min = Math.min(min, x < min_thresh ? 0 : x, y < min_thresh ? 0 : y);
        }

        const header = new Uint16Array(buffer, (bufferIndex += 6));

        header[0] = state.dft_cutoff[component]; // Length of associated body
        header[1] = min; // Minimum non-zero representable value
        header[2] = max; // Maximum representable value

        // Body

        const body = new Uint8Array(buffer);

        // Push all elements into body in x/y order
        for (let i = 0; i < state.dft_cutoff[component]; i++) {
            const v = state.dft[component][i];

            const x = v.re();
            const y = v.im();

            body[bufferIndex++] = x;
            body[bufferIndex++] = y;
        }
    }

    return buffer;
}
registerCompressor(computeCompressionSize);

// Mime image being uploaded
uploadInput(new URL("../microtest.png", import.meta.url));
